export { setToLocalStorage } from './setToLocalStorage'
export { localStorage } from './localStorage'
export { getFromLocalStorage } from './getFromLocalStorage'
export { getDate } from './getDate'
export { findTaskId } from './findTaskId'
export { getSortedTasks } from './getSortedTasks'
